// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdayqoehopgsxghchpcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkYXlxb2Vob3Bnc3hnaGNocGNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzk1ODUsImV4cCI6MjA3MzQxNTU4NX0.wUxZI31LaQ7piZxayoC4D6ZopZ-ADehkpUr4vk41gMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});